### PR TITLE
Fix stop time in ExternalPlayer

### LINKED ISSUE #565: External player sends wrong stopped timestamps
### Please describe your bug

Steps to reproduce:
- Configure the Jellyfin Android client to use MPV as external player
- Play a video starting from the beginning for 5 minutes (seeking to 5 minutes works, too)
- Stop
- Resume the same video (it starts correctly at the 5 minute mark). Play another minute until you reach the playback position 6:00
- Stop
- You might be able to tell by the blue progress bar that new resume position is wrong. It's suddently jumpted to 11 minutes instead of the 6 minute mark.
- Resuming the same video confirms this suspicion. It starts at 11:00 instead of 6:00. Somehow, the resume time that jellyfin stores is the *sum* of the previous actual two instead of just the last one.

I'm not sure which side is to blame here. The server side or the client side. So, I'm opening the issue here.

According to the attached jellyfin logs, the wrong time stamps also appear as reported by the client:

```
[2021-11-16 11:50:05.531 +01:00] [INF] Playback stopped reported by app "Jellyfin Android" "2.4.0" playing "Episode 1". Stopped at "300342" ms
...
[2021-11-16 11:50:23.471 +01:00] [INF] Playback stopped reported by app "Jellyfin Android" "2.4.0" playing "Episode 1". Stopped at "660951" ms
```

The second time stamp should be around 360000 ms (6:00). So, if that is really what the client was reporting, the client is at fault, I guess. But it might also be a value (wrongly) adjusted by the server -- maybe because the server *thinks* the client's "epoch" (0:00) starts at 5:00 (last resume point).

### Jellyfin Version

10.7.7

### if other:

_No response_

### Environment

```markdown
- OS: Debian Linux
- Virtualization: No
- Clients: Android client with MPV as external player
```

### Jellyfin logs

```shell
[2021-11-16 11:49:39.505 +01:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: "Android External Player Stub", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 100000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 320000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [], TranscodingProfiles: [], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [] }
[2021-11-16 11:49:39.509 +01:00] [INF] User policy for "jellyfin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-11-16 11:49:39.510 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2021-11-16 11:49:39.510 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2021-11-16 11:49:39.510 +01:00] [INF] Profile: "Android External Player Stub", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2021-11-16 11:49:39.511 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2021-11-16 11:49:39.512 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2021-11-16 11:49:39.512 +01:00] [INF] Profile: "Android External Player Stub", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2021-11-16 11:49:39.513 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2021-11-16 11:49:39.513 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2021-11-16 11:49:39.514 +01:00] [INF] Profile: "Android External Player Stub", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2021-11-16 11:49:39.594 +01:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: "Android External Player", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 2147483647, MaxAlbumArtHeight: 2147483647, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Video }, DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [SubtitleProfile { Format: "ssa", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "idx", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "vtt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "webvtt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ttml", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smil", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "idx", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "webvtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ttml", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smil", Method: External, DidlMode: null, Language: null, Container: null }] }
[2021-11-16 11:49:39.602 +01:00] [INF] User policy for "jellyfin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-11-16 11:49:39.602 +01:00] [INF] Profile: "Android External Player", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-11-16 11:49:39.603 +01:00] [INF] Profile: "Android External Player", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-11-16 11:49:39.603 +01:00] [INF] Profile: "Android External Player", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-11-16 11:49:40.100 +01:00] [INF] Starting User Changes Sync...
[2021-11-16 11:49:40.126 +01:00] [INF] "USERSYNC" User "2900a229289d453c900e256b6d66931e"("jellyfin") posted 2 Updates: "925739bb5214edc376272c346368253f,943468baaaa2d0f84e5f8ca3786cf0ef"
[2021-11-16 11:49:40.127 +01:00] [INF] User Changes Sync Finished Taking "00:00:00.0258807"
[2021-11-16 11:49:46.570 +01:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-11-16 11:49:58.574 +01:00] [INF] Lost 1 WebSockets.
[2021-11-16 11:50:05.531 +01:00] [INF] Playback stopped reported by app "Jellyfin Android" "2.4.0" playing "Episode 1". Stopped at "300342" ms
[2021-11-16 11:50:06.050 +01:00] [INF] Starting User Changes Sync...
[2021-11-16 11:50:06.073 +01:00] [INF] "USERSYNC" User "2900a229289d453c900e256b6d66931e"("jellyfin") posted 2 Updates: "925739bb5214edc376272c346368253f,943468baaaa2d0f84e5f8ca3786cf0ef"
[2021-11-16 11:50:06.073 +01:00] [INF] User Changes Sync Finished Taking "00:00:00.0229354"
[2021-11-16 11:50:09.027 +01:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: "Android External Player Stub", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 100000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 320000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [], TranscodingProfiles: [], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [] }
[2021-11-16 11:50:09.028 +01:00] [INF] User policy for "jellyfin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-11-16 11:50:09.028 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2021-11-16 11:50:09.028 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2021-11-16 11:50:09.028 +01:00] [INF] Profile: "Android External Player Stub", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2021-11-16 11:50:09.028 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2021-11-16 11:50:09.028 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2021-11-16 11:50:09.028 +01:00] [INF] Profile: "Android External Player Stub", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2021-11-16 11:50:09.028 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2021-11-16 11:50:09.028 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2021-11-16 11:50:09.028 +01:00] [INF] Profile: "Android External Player Stub", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2021-11-16 11:50:09.070 +01:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: "Android External Player", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 2147483647, MaxAlbumArtHeight: 2147483647, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Video }, DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [SubtitleProfile { Format: "ssa", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "idx", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "vtt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "webvtt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ttml", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smil", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "idx", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "webvtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ttml", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smil", Method: External, DidlMode: null, Language: null, Container: null }] }
[2021-11-16 11:50:09.072 +01:00] [INF] User policy for "jellyfin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-11-16 11:50:09.072 +01:00] [INF] Profile: "Android External Player", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-11-16 11:50:09.072 +01:00] [INF] Profile: "Android External Player", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-11-16 11:50:09.072 +01:00] [INF] Profile: "Android External Player", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-11-16 11:50:09.612 +01:00] [INF] Starting User Changes Sync...
[2021-11-16 11:50:09.652 +01:00] [INF] "USERSYNC" User "2900a229289d453c900e256b6d66931e"("jellyfin") posted 2 Updates: "925739bb5214edc376272c346368253f,943468baaaa2d0f84e5f8ca3786cf0ef"
[2021-11-16 11:50:09.652 +01:00] [INF] User Changes Sync Finished Taking "00:00:00.0396976"
[2021-11-16 11:50:23.471 +01:00] [INF] Playback stopped reported by app "Jellyfin Android" "2.4.0" playing "Episode 1". Stopped at "660951" ms
[2021-11-16 11:50:23.988 +01:00] [INF] Starting User Changes Sync...
[2021-11-16 11:50:24.010 +01:00] [INF] "USERSYNC" User "2900a229289d453c900e256b6d66931e"("jellyfin") posted 2 Updates: "925739bb5214edc376272c346368253f,943468baaaa2d0f84e5f8ca3786cf0ef"
[2021-11-16 11:50:24.011 +01:00] [INF] User Changes Sync Finished Taking "00:00:00.0227514"
[2021-11-16 11:50:26.099 +01:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: "Android External Player Stub", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 100000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 320000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [], TranscodingProfiles: [], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [] }
[2021-11-16 11:50:26.100 +01:00] [INF] User policy for "jellyfin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-11-16 11:50:26.101 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2021-11-16 11:50:26.101 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2021-11-16 11:50:26.101 +01:00] [INF] Profile: "Android External Player Stub", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2021-11-16 11:50:26.101 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2021-11-16 11:50:26.101 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2021-11-16 11:50:26.101 +01:00] [INF] Profile: "Android External Player Stub", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2021-11-16 11:50:26.104 +01:00] [INF] Not eligible for DirectPlay due to unsupported subtitles
[2021-11-16 11:50:26.104 +01:00] [INF] Not eligible for DirectStream due to unsupported subtitles
[2021-11-16 11:50:26.104 +01:00] [INF] Profile: "Android External Player Stub", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[2021-11-16 11:50:26.144 +01:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: "Android External Player", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 2147483647, MaxAlbumArtHeight: 2147483647, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Video }, DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [SubtitleProfile { Format: "ssa", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "idx", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "vtt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "webvtt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ttml", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smil", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "idx", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "webvtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ttml", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smil", Method: External, DidlMode: null, Language: null, Container: null }] }
[2021-11-16 11:50:26.145 +01:00] [INF] User policy for "jellyfin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-11-16 11:50:26.145 +01:00] [INF] Profile: "Android External Player", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-11-16 11:50:26.145 +01:00] [INF] Profile: "Android External Player", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-11-16 11:50:26.146 +01:00] [INF] Profile: "Android External Player", Path: "/mnt/merged_share/some_video.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-11-16 11:50:26.681 +01:00] [INF] Starting User Changes Sync...
[2021-11-16 11:50:26.705 +01:00] [INF] "USERSYNC" User "2900a229289d453c900e256b6d66931e"("jellyfin") posted 2 Updates: "925739bb5214edc376272c346368253f,943468baaaa2d0f84e5f8ca3786cf0ef"
[2021-11-16 11:50:26.705 +01:00] [INF] User Changes Sync Finished Taking "00:00:00.0237393"
[2021-11-16 11:50:31.545 +01:00] [INF] Playback stopped reported by app "Jellyfin Android" "2.4.0" playing "Episode 1". Stopped at "1323487" ms
[2021-11-16 11:50:32.060 +01:00] [INF] Starting User Changes Sync...
[2021-11-16 11:50:32.085 +01:00] [INF] "USERSYNC" User "2900a229289d453c900e256b6d66931e"("jellyfin") posted 2 Updates: "925739bb5214edc376272c346368253f,943468baaaa2d0f84e5f8ca3786cf0ef"
[2021-11-16 11:50:32.085 +01:00] [INF] User Changes Sync Finished Taking "00:00:00.0246603"
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Maxr1998**
Previously, since the web client thought the external player was transcoding, due to a stubbed device profile, it added the transcoding offset to the current time on playback stop, sending the wrong value to the server. Simply marking all content as direct-playable fixes this.
Additionally, some timestamp handling issues related to ticks vs milliseconds were fixed.

Fixes #565.

### CODE REVIEW

File: app/src/main/assets/native/ExoPlayerPlugin.js [hunk 1]
```diff
@@ -163,17 +163,15 @@ export class ExoPlayerPlugin {
...
-        profile.MusicStreamingTranscodingBitrate = 320000;
-
-        profile.DirectPlayProfiles = [];
-        profile.CodecProfiles = [];
-        profile.SubtitleProfiles = [];
-        profile.TranscodingProfiles = [];
-
-        return profile;
+        return {
+            'Name': 'ExoPlayer Stub',
```
Comment (nielsvanvelzen) [inline app/src/main/assets/native/ExoPlayerPlugin.js:167]: Object keys in JS don't need to be quoted:

```suggestion
            Name: 'ExoPlayer Stub',
```

(same for the keys in the DirectPlayProfiles array)

File: app/src/main/assets/native/ExternalPlayerPlugin.js [hunk 2]
```diff
@@ -101,9 +102,8 @@ export class ExternalPlayerPlugin {
     }
 
     async notifyTimeUpdate(currentTime) {
-        // if no time provided handle like playback completed
-        currentTime = currentTime || this.playbackManager.duration(this);
-        currentTime = currentTime / 1000;
+        // If no time is, use duration (as if playback completed)
```
Comment (nielsvanvelzen) [inline app/src/main/assets/native/ExternalPlayerPlugin.js:105]:
```suggestion
        // If no time is provided, use duration (as if playback completed)
```

```suggestion
        // Use duration (as if playback completed) if no time is provided
```

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]

File: app/src/main/assets/native/ExoPlayerPlugin.js (hunk 1 above)
Comment (Maxr1998) [reply app/src/main/assets/native/ExoPlayerPlugin.js:167]: Copied from JMP, oops. Gonna fix.

**Review by nielsvanvelzen — APPROVED** [review]
