### PR TITLE
Use display language when available

### LINKED ISSUE #83: "Client settings" parameter page not following the user display language
**Describe the bug**
The "client settings" parameter page doesn't follow the display language used by the logged user but the language used by Android.

**To Reproduce**

1. Set a display language different than the phone's
2. Restart the app to apply the changes
3. Go to "client settings" and see the strings displayed in the phone's language

**Expected behavior**
It should use the display language specified by the user.

**System (please complete the following information):**
 - App version: 2.0.0-rc.3
 - Android version: Android 8
 - Device manufacturer and model: Samsung Galaxy A5 2017
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: N/A

### PR DESCRIPTION
**Pull request by CarlosOlivo**
In the next order:
1. User settings
2. ~~Server settings~~
3. Android settings

For now, it's necessary to restart the application manually when the language is changed, as long as no [events](https://github.com/jellyfin/jellyfin-web/blob/c8b6b44b7bf79c5a14055c6262b85b5af9cd7554/src/scripts/globalize.js#L259) are handled.

Closes #83

### CODE REVIEW

File: app/src/main/java/org/jellyfin/mobile/MainActivity.kt [hunk 1]
```diff
@@ -194,6 +196,55 @@ class MainActivity : AppCompatActivity(), WebViewController {
         if (connectionHelper.connected) webView.loadUrl(url)
     }
 
+    @Suppress("DEPRECATION")
+    private fun initLocale() {
+        runOnUiThread {
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/MainActivity.kt:201]: The extra `runOnUiThread` shouldn't be necessary.

File: app/src/main/java/org/jellyfin/mobile/MainActivity.kt [hunk 2]
```diff
@@ -194,6 +196,55 @@ class MainActivity : AppCompatActivity(), WebViewController {
...
+            webView.evaluateJavascript("window.localStorage.getItem('${apiClient.currentUserId}-language')") { result ->
+                if (!setLocale(result.unescapeJson(), "userSettings")) {
+                    GlobalScope.launch {
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/MainActivity.kt:204]: Don't use GlobalScope, it should only be used in very rare circumstances.
```suggestion
                    lifecycleScope.launch {
```

File: app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt [hunk 3]
```diff
@@ -18,6 +18,7 @@ class SettingsActivity : AppCompatActivity() {
 
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
+        setTitle(R.string.activity_name_settings)
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt:21]: This shouldn't be necessary, as it's already set in the manifest.

File: app/src/main/java/org/jellyfin/mobile/utils/ApiExtensions.kt [hunk 4]
```diff
@@ -33,6 +34,10 @@ suspend fun ApiClient.markPlayed(itemId: String, userId: String): UserItemDataDt
     MarkPlayedAsync(itemId, userId, Date(), ContinuationResponse(continuation))
 }
 
+suspend fun ApiClient.getServerConfigurationAsync(): ServerConfiguration? = suspendCoroutine { continuation ->
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/utils/ApiExtensions.kt:37]: To be more in line with the other functions:
```suggestion
suspend fun ApiClient.getServerConfiguration(): ServerConfiguration? = suspendCoroutine { continuation ->
```

Also, you can move this below `getPublicSystemInfo`.

File: app/src/main/java/org/jellyfin/mobile/MainActivity.kt [hunk 5]
```diff
@@ -194,6 +196,55 @@ class MainActivity : AppCompatActivity(), WebViewController {
...
+                val language = culture.split('-')
+                if (language.size == 2) {
+                    appPreferences.language = language[0]
+                    appPreferences.country = language[1]
+                }
+            } else {
+                appPreferences.language = culture
+                appPreferences.country = ""
+            }
+            Timber.d("initLocale [method: $method, language: '${appPreferences.language}', country: '${appPreferences.country}']")
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/MainActivity.kt:242]:
```suggestion
            Timber.d("setLocale [method: $method, language: '${appPreferences.language}', country: '${appPreferences.country}']")
```

**Review by Maxr1998 — CHANGES_REQUESTED** [review]
Thanks for the PR!
Apart from my review comments, could you maybe move those function to another file/class as well? Maybe even with dependency injection, scoped to the Activity. See the [Koin docs](https://start.insert-koin.io/#/getting-started/koin-for-android?id=extended-scope-api) for more info on that.

File: app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt (hunk 3 above)
Comment (CarlosOlivo) [reply app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt:23]: Unfortunately it's necessary to load a new translation or something like that.

**Without setTtile**
image


**With setTitle**
image

**Comment by Maxr1998** [comment]
Thanks for the changes! I'll review this later today (after sleeping).

File: app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+    val configuration = resources.configuration
+    val locale = Locale(
+        language ?: configuration.locale.language,
+        country ?: configuration.locale.country
+    )
+    Timber.d("loadLocale [class: ${localClassName}, language: '${locale.language}', country: '${locale.country}']")
+    Locale.setDefault(locale)
+    configuration.setLocale(locale)
+    resources.updateConfiguration(configuration, resources.displayMetrics)
+}
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt:38]: Could you merge this function into the `setLocale` function? Then you could also keep the language/locale variables inside `setLocale`, and wouldn't require the global ones.

File: app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+
+private fun Activity.setLocale(culture: String?, method: String): Boolean {
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt:40]:
```suggestion
private fun Activity.setLocale(localeString: String?, source: String): Boolean {
```

**Review by Maxr1998 — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt [hunk 8]
```diff
@@ -0,0 +1,53 @@
...
+}
+
+@Suppress("DEPRECATION")
+private fun Activity.setLocale(localeString: String?, source: String): Boolean {
+    var language: String? = null
+    var country: String? = null
+
+    if (localeString.isNullOrEmpty() || localeString == "null") {
+        return false
+    } else {
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt:31]: I'd invert the if condition, to cover the success case first

File: app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt [hunk 9]
```diff
@@ -0,0 +1,53 @@
...
+        if (localeString.contains('-')) {
+            val cultureSplit = localeString.split('-')
+            if (cultureSplit.size == 2) {
+                language = cultureSplit[0]
+                country = cultureSplit[1]
+            }
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt:37]:
```suggestion
            } else {
                return false
            }
```

File: app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt [hunk 10]
```diff
@@ -0,0 +1,53 @@
...
+        }
+        Timber.d("setLocale [source: $source, language: '${language}', country: '${country}']")
+        val configuration = resources.configuration
+        val locale = Locale(
+            language ?: configuration.locale.language,
+            country ?: configuration.locale.country
+        )
+        Locale.setDefault(locale)
+        configuration.setLocale(locale)
+        resources.updateConfiguration(configuration, resources.displayMetrics)
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt:50]: Could you only update the configuration if there's actually a locale set, and maybe even check if the locales differ?

**Review by Maxr1998 — CHANGES_REQUESTED** [review]

**Review by Maxr1998 — APPROVED** [review]

**Comment by Maxr1998** [comment]
@CarlosOlivo did some more tweaks, please take another look at those and lmk if the are correct, then I'll merge.
@nielsvanvelzen would also appreciate a review from you :grin:

**Comment by CarlosOlivo** [comment]
> @CarlosOlivo did some more tweaks, please take another look at those and lmk if they are ok, then I'll merge.
> @nielsvanvelzen would also appreciate a review from you 😁

Yep, it works fine, you just have to remove all the code that loads the locale from the API [serverSettings], I noticed after the next test that it is not necessary and even counterproductive.

1. Set client setting locale [userSettings] to Auto or clear App Data
2. Set android system locale to English (United States) [es_US]
3. Set jellyfin server locale [uiCulture] to Spanish (México) [es-MX]

With serverSettings code:

- 2020-09-21 00:43:40.491 3417-3417/org.jellyfin.mobile.debug D/LocaleUtilsKt: Updated locale from [serverSettings], locale: 'es_MX'
- webView: English (United States) [es_US]
- settingsActivity: Spanish (México) [es_MX]

Without serverSettings code:

- 2020-09-21 00:49:29.693 3422-3422/org.jellyfin.mobile.debug D/LocaleUtilsKt$initLocale: Couldn't acquire locale from config, keeping current
- webView: English (United States) [es_US]
- settingsActivity: English (United States) [es_US]

File: app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt [hunk 11]
```diff
@@ -0,0 +1,57 @@
...
+    }
+
+    val configuration = resources.configuration
+    if (locale != configuration.primaryLocale) {
+        Locale.setDefault(locale)
+        configuration.setLocale(locale)
+        @Suppress("DEPRECATION")
+        resources.updateConfiguration(configuration, resources.displayMetrics)
+
+        Timber.d("Updated locale from [$source], locale: '$locale'")
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt:50]:
```suggestion
        Timber.i("Updated locale from [$source], locale: '$locale'")
```

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]

**Comment by Maxr1998** [comment]
@CarlosOlivo So I should just keep the user settings source for locale?

**Comment by CarlosOlivo** [comment]
> @CarlosOlivo So I should just keep the user settings source for locale?

Yep, when no language is set in user settings the web UI fallback to system locale, not to uiCulture locale.

https://github.com/jellyfin/jellyfin-web/blob/7f8019d01f73a235edbd3e7872cf44310ce013e1/src/scripts/globalize.js#L39

https://github.com/jellyfin/jellyfin-web/blob/7f8019d01f73a235edbd3e7872cf44310ce013e1/src/scripts/globalize.js#L20

That is the default behavior.

**Review by Maxr1998 — APPROVED** [review]

File: app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt (hunk 11 above)
Comment (nielsvanvelzen) [reply app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt]: This one isn't resolved.

Comment (Maxr1998) [reply app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt]: > This one isn't resolved.

Yikes, I only fixed the other one..

**Review by nielsvanvelzen — APPROVED** [review]
