### PR TITLE
Fix VLC external player crashing on Android 13

### LINKED ISSUE #912: VLC Player Crash
### Describe the bug

I'm on a Galaxy Tab S8 Plus (tablet) running android 13, I've got the jellyfin android app installed with the video player set to external.
The external video player selected is VLC Player. 
When I hit play on any video the app crashes to desktop (home screen) with no error code.
When I relaunch the app it says it crashed and offers to clear cache but doing this does not help. 
I've tried the Web player, Exo player and MPV (external) and all three work. Only VLC player causes this crash.
Have used VLC as external on other devices with no issues, only encountered this after trying it on my new tablet. 

### Logs

_No response_

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Galaxy Tab S8 Plus

### Android version

Android 13

### Jellyfin server version

10.8.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

### PR DESCRIPTION
**Pull request by Maxr1998**
**Changes**
Due to security-related changes in Android 13, the entrypoint must be the default start activity.

This requires https://code.videolan.org/videolan/vlc-android/-/merge_requests/1738 to be merged and released for playback tracking to work again.

**Issues**
Fixes #912

### CODE REVIEW

File: app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt [hunk 1]
```diff
@@ -334,7 +334,7 @@ class ExternalPlayer(
                 ComponentName(packageName, "$packageName.ActivityScreen")
             }
             ExternalPlayerPackage.VLC_PLAYER -> {
-                ComponentName(packageName, "$packageName.gui.video.VideoPlayerActivity")
+                ComponentName(packageName, "$packageName.StartActivity")
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt:337]: Do we want to add a version check here so users with an older version of the VLC app don't need to update on Android 12<=?

Comment (Maxr1998) [reply app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt:337]: I don't think so, it'll still work, just not have progress tracking.
Also I'm not even sure the recent VLC updates didn't break it anyway on all versions.

**Review by nielsvanvelzen — APPROVED** [review]
