### PR TITLE
Fix module script injection

### LINKED ISSUE #453: Players cannot be switched on some models
**Describe the bug**
On my Xperia xz1 Xperia z3c, I can't switch to exoplayer, but oneplus 7tpro can switch normally

**To Reproduce**
1. Enter the setting and switch to exoplayer or mxplayer
2. Play the video
3. It's still an HTML player

**Expected behavior**
Switch player

**Logs**
No, I need some time to find the computer

**Screenshots**
Screenshot_20210626-025358
Screenshot_20210626-025330

**System (please complete the following information):**
 - App version: 2.3.0 beta6
 - Device manufacturer , model and Android version: 
 
 Unable to switch：
 Xperia xz1(android9) Xperia Z3 (android6) 

Normal switch：
 OnePlus7tpro(OOS11,ANDROID 11)

 - Jellyfin server version: 10.7.5
 - The type of video player implementation used: web player , native player (ExoPlayer) or external player (mpv, VLC)

**Additional context**
nothing

### LINKED ISSUE #456: Back button click does not work
**Describe the bug**

Wherever you are in the app clicking back button does not work while clicking arrow top left to go back works.

**To Reproduce**

Open app and click back button.

**Expected behavior**

Back button should take me back to previous screen or exit the app.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - App version: latest from google play store
 - Android version: Android 9
 - Device manufacturer and model: Sony Xperia xz premium
 - Jellyfin server version: latest from official website
 - The type of video player implementation used: default

**Additional context**

### PR DESCRIPTION
**Pull request by CarlosOlivo**
See https://github.com/jellyfin/jellyfin-android/issues/453#issuecomment-873984436

Closes #453
Closes #456

### CODE REVIEW

File: app/src/main/java/org/jellyfin/mobile/utils/WebViewUtils.kt [hunk 1]
```diff
@@ -71,3 +73,19 @@ fun WebSettings.applyDefault() {
...
+ *
+ * @see WebViewAssetLoader.AssetsPathHandler.handle
+ */
+fun WebViewAssetLoader.AssetsPathHandler.inject(path: String): WebResourceResponse? {
+    return handle(path)?.apply {
+        if (path.endsWith(".js", ignoreCase = true)) {
+            mimeType = "application/javascript"
+        }
+    }
+}
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/utils/WebViewUtils.kt:91]: I'd argue that ignoring case isn't necessary, but I suppose it doesn't hurt either. Still, I suggest collapsing the body to an `=` statement / removing the return.

File: app/src/main/java/org/jellyfin/mobile/utils/WebViewUtils.kt [hunk 2]
```diff
@@ -71,3 +73,19 @@ fun WebSettings.applyDefault() {
     javaScriptEnabled = true
     domStorageEnabled = true
 }
+
+/**
+ * Opens the requested file from the application's assets directory.
+ *
+ * By default Android doesn't provide the javascript MIME type,
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/utils/WebViewUtils.kt:80]:
```suggestion
 * On some devices Android doesn't set the JavaScript MIME type,
```

File: app/src/main/java/org/jellyfin/mobile/utils/WebViewUtils.kt [hunk 3]
```diff
@@ -71,3 +73,19 @@ fun WebSettings.applyDefault() {
...
+ * return "application/javascript" when required.
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/utils/WebViewUtils.kt:81]:
```suggestion
 * thus manually set it to "application/javascript" where applicable.
```

**Review by Maxr1998 — CHANGES_REQUESTED** [review]

**Review by Maxr1998 — APPROVED** [review]
