### PR TITLE
Fix various playback crashes

### LINKED ISSUE #371: Crash when trying to play using external player
**Describe the bug**
The app crashes when trying to play a video with `Video player type` set to `External player`, both with `External player app` set to `System default` and `VLC Player`

**To Reproduce**
1. Set video player type to external player in client settings
2. Try to play a video

**Expected behavior**
The app opens the video in the external player

**Logs**
```AndroidRuntime: FATAL EXCEPTION: main
05-07 22:05:28.108  7273  7273 E AndroidRuntime: Process: org.jellyfin.mobile, PID: 7273
05-07 22:05:28.108  7273  7273 E AndroidRuntime: java.lang.NullPointerException
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at org.jellyfin.mobile.bridge.ExternalPlayer$initPlayer$1.invokeSuspend(ExternalPlayer.kt:5)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at n.n.k.a.a.resumeWith(ContinuationImpl.kt:3)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at o.a.l0.run(DispatchedTask.kt:18)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7660)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-07 22:05:28.108  7273  7273 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Screenshots**

https://user-images.githubusercontent.com/55142207/117506034-3b940680-af85-11eb-8943-4c43c91a600c.mp4

**System (please complete the following information):**
 - App version: 2.3.0-beta.1
 - Android version: 11 (LineageOS 18.1)
 - Device manufacturer and model: Oneplus 3T
 - Jellyfin server version: 10.7.5
 - The type of video player implementation used: external player (VLC)

**Additional context**
Didn't happen in previous version

### PR DESCRIPTION
**Pull request by Maxr1998**
Fixes #371, #370, #368.

### CODE REVIEW

File: app/src/main/assets/native/ExternalPlayerPlugin.js [hunk 1]
```diff
@@ -45,7 +45,9 @@ export class ExternalPlayerPlugin {
         this._paused = false;
         this._currentSrc = options.url;
         this._isIntro = options.item && options.item.ProviderIds && options.item.ProviderIds.hasOwnProperty("prerolls.video");
-        this._externalPlayer.initPlayer(JSON.stringify(options.item.playOptions));
+        let playOptions = options.item.playOptions;
```
Comment (nielsvanvelzen) [inline app/src/main/assets/native/ExternalPlayerPlugin.js:48]:
```suggestion
        const playOptions = options.item.playOptions;
```

File: app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt [hunk 2]
```diff
@@ -74,18 +75,30 @@ class ExternalPlayer(
...
                 deviceProfile = externalPlayerProfile,
                 startTimeTicks = playOptions.startPositionTicks,
                 audioStreamIndex = playOptions.audioStreamIndex,
                 subtitleStreamIndex = playOptions.subtitleStreamIndex,
-            ) ?: return@launch
-
-            playMediaSource(playOptions, jellyfinMediaSource)
+            ).onSuccess { jellyfinMediaSource ->
+                playMediaSource(playOptions, jellyfinMediaSource)
+            }.onFailure { error ->
```
Comment (dkanada) [inline app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt:94]: Is this an ExoPlayer thing or a Kotlin thing?

Comment (nielsvanvelzen) [reply app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt:94]: It's the Result class
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result/

**Review by nielsvanvelzen — APPROVED** [review]
