### PR TITLE
Ensure ExternalPlayer always direct plays

### LINKED ISSUE #970: Discouraging external player from playing some videos
### Describe the bug

When using external players(MX Player Pro for me), some videos can't be played by clicking the "play" icon in Jellyfin app.It toasts "Media cannot be played by this device".

Snipaste_2023-02-09_23-02-01

But if you "Copy stream URL" and use MX Player to play, MX Player actually could play that normally.

Even if using the "Web player" or "Integrated player" that works fine!

After checking the source code I found it was caused by the `DeviceProfileBuilder.getExternalPlayerProfile()` created a `DeviceProfile` declares far few play profiles decoders than MX Player (or VLC) has.

Snipaste_2023-02-09_22-23-15

Snipaste_2023-02-09_22-19-33

, so when request `mediaInfoApi.getPostedPlaybackInfo()` with that play profile, server returns 

```
    ...
    "SupportsTranscoding": false,
    "SupportsDirectStream": false,
    "SupportsDirectPlay": false,
    ...
```

,then `JellyfinMediaSource` failed to find a valid play method and throw `"No play method found for $name ($itemId)"`

The temporary solution is to change the generator for `externalPlayerProfile` in class `ExternalPlayer`, use `deviceProfileBuilder.getDeviceProfile()` since external players could play videos supported by the device,I would put a new pull request later.But a better solution is to let `JellyfinMediaSource` know whether `appPreferences.videoPlayerType == VideoPlayerType.EXTERNAL_PLAYER` and let it go when "No play method found",since external players are generally strong,like this :
Snipaste_2023-02-09_23-11-14

I'm not familiar with Kotlin so I didn't do so.Looking forward to your suggestion!

### Logs

```shell
E/MediaSourceResolver: Cannot create JellyfinMediaSource
    java.lang.IllegalArgumentException: No play method found for VIDEO_TITLE_HERE (ITEM_ID_HERE)
        at org.jellyfin.mobile.player.source.JellyfinMediaSource.<init>(JellyfinMediaSource.kt:29)
        at org.jellyfin.mobile.player.source.MediaSourceResolver.resolveMediaSource-eH_QyT8(MediaSourceResolver.kt:71)
        at org.jellyfin.mobile.player.source.MediaSourceResolver$resolveMediaSource$1.invokeSuspend(Unknown Source:21)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Application version

2.5.0

### Where did you install the app from?

Sideloaded APK (libre build)

### Device information

Xiaomi 10, Pixel 6 Pro(VM)

### Android version

Android 12(MIUI 13), Android 13

### Jellyfin server version

10.8.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

### PR DESCRIPTION
**Pull request by Maxr1998**
Instead of using a device profile like for ExoPlayer, we always build the direct stream URL, and at the same time tweak the media source request so that it never suggests transcoding. We do that by supplying an effectively unlimited maximum bit rate, which was previously hard-coded to 120 Mbps through the device profile.

Fixes #970.

### CODE REVIEW

File: app/src/main/assets/native/ExternalPlayerPlugin.js [hunk 1]
```diff
@@ -141,12 +141,11 @@ export class ExternalPlayerPlugin {
     async getDeviceProfile() {
         return {
             Name: 'Android External Player Stub',
-            MaxStreamingBitrate: 100000000,
-            MaxStaticBitrate: 100000000,
-            MusicStreamingTranscodingBitrate: 320000,
+            MaxStreamingBitrate: 1000000000,
+            MaxStaticBitrate: 1000000000,
```
Comment (nielsvanvelzen) [inline app/src/main/assets/native/ExternalPlayerPlugin.js:145]:
```suggestion
            MaxStreamingBitrate: 1_000_000_000,
            MaxStaticBitrate: 1_000_000_000,
```

File: app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt [hunk 2]
```diff
@@ -205,7 +167,8 @@ class ExternalPlayer(
     }
 
     private fun notifyEvent(event: String, parameters: String = "") {
-        if (event in arrayOf(Constants.EVENT_CANCELED, Constants.EVENT_ENDED, Constants.EVENT_TIME_UPDATE) && parameters == parameters.filter { it.isDigit() }) {
+        val allowedEvents = arrayOf(Constants.EVENT_CANCELED, Constants.EVENT_ENDED, Constants.EVENT_TIME_UPDATE)
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt:170]: Should this be a companion object constant?

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt (hunk 2 above)
Comment (Maxr1998) [reply app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt]: I suppose it would be better, yes.

**Review by nielsvanvelzen — APPROVED** [review]
