### PR TITLE
Fix background playback stopping on Android 14

### LINKED ISSUE #1378: Music playback stops when app is in the background
### Describe the bug

I am using a Google Pixel 6 and have app battery usage set to 'unrestricted' - see screenshot - but as soon as I switch away from having the app in the foreground music playback stops. This makes it unusable for audio playback. None of my other audio apps have this problem, e.g. Spotify; VLC.

As per [previous bug report](https://github.com/jellyfin/jellyfin-android/issues/1208) I see a trail of reports of this same issue here on GitHub https://github.com/jellyfin/jellyfin-android/issues/948 and elsewhere, e.g. [Reddit](https://www.reddit.com/r/jellyfin/comments/jfkuij/jellyfin_stops_playing_next_song_if_jellyfin_is/) but no solutions. In each case we see the issue was closed by a bot without effective resolution. 

In my case I am not using a VPN

303915035-db97c12d-27aa-41c7-aa46-19e1196d2847

### Logs

_No response_

### Application version

2.6.1

### Where did you install the app from?

Google Play

### Device information

Google Pixel 6

### Android version

Android 14

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

### LINKED ISSUE #1401: Jellyfin pauses music playback after 20 - 30 seconds of the app being in the background
### Describe the bug

I play a song on the app, exit out and it continues playing, then after 30 seconds or so it stops and will only play again once I click on the app. I use graphene os if that has anything to do with it? I disabled all the graphene os memory stuff for the app but it still doesnt work. Battery optimisation is on unoptimised. Thanks

### Logs

_No response_

### Application version

2.6.1

### Where did you install the app from?

F-Droid

### Device information

Google Pixel 7

### Android version

Graphene OS

### Jellyfin server version

10.8.13

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [X] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

### PR DESCRIPTION
**Pull request by michd**
`RemotePlayerService` service was not being properly started as a foreground service for media playback, causing playback stoppage after every track (or sooner for some folks), on android 14.

Different vendors may be more or less aggressive with killing of non-foreground service etc, so people may have gotten different results from the same root issue.

**Changes**
- Changes the manifest entry for `RemotePlayerService` to include the `foregroundServiceType="mediaPlayback"` attribute (see ["Foreground service types are required"](https://developer.android.com/about/versions/14/behavior-changes-14#fgs-types))
- Declares the foreground service behavior as part of the notification (see same req)
- Uses `startForeground` instead of `notificationManager.notify`
- Uses `ContextCompat.startForegroundService` to send intents to the service

Some of these changes can also be found in @dumpfheimer's PR [Improving Chromecast Integration #1298](https://github.com/jellyfin/jellyfin-android/pull/1298)

**Issues**

- Fixes #1378
- Fixes #1401

---

(For a bit of my background: my day job is working on a music streaming android app and we've previously hit similar issues)

### CODE REVIEW

File: app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt [hunk 1]
```diff
@@ -263,6 +264,11 @@ class RemotePlayerService : Service(), CoroutineScope {
                 } else {
                     setPriority(Notification.PRIORITY_LOW)
                 }
+
+                if (AndroidVersion.isAtLeastS) {
+                    setForegroundServiceBehavior(Notification.FOREGROUND_SERVICE_IMMEDIATE)
+                }
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt:270]: Might not be necessary [since the `foregroundServiceType` in the manifest is `mediaPlayback`](https://developer.android.com/develop/background-work/services/foreground-services#notification-immediate).

File: app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt [hunk 2]
```diff
@@ -340,7 +346,18 @@ class RemotePlayerService : Service(), CoroutineScope {
...
+                    MEDIA_PLAYER_NOTIFICATION_ID,
+                    notification,
+                    ServiceInfo.FOREGROUND_SERVICE_TYPE_MANIFEST
+                )
+            } else {
+                startForeground(
+                    MEDIA_PLAYER_NOTIFICATION_ID,
+                    notification
+                )
+            }
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt:360]: Could use [`ServiceCompat.startForeground()`](https://developer.android.com/reference/androidx/core/app/ServiceCompat#startForeground(android.app.Service,int,android.app.Notification,int)) instead.

**Review by Maxr1998 — COMMENTED** [review]
Looks good, have a few comments nonetheless. Please also fix the lint failure (should be the missing trailing comma, I think).

File: app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt (hunk 2 above)
Comment (michd) [reply app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt:360]: True, however the [`ServiceInfo.FOREGROUND_SERVICE_TYPE_MANIFEST`](https://developer.android.com/reference/android/content/pm/ServiceInfo#FOREGROUND_SERVICE_TYPE_MANIFEST) constant was only added in API level 29, so it either requires a version check, or has to be duplicated locally. I think I prefer the current way over that. What's your preference?

File: app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt (hunk 1 above)
Comment (michd) [reply app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt]: Oh yeah thank you, that's indeed redundant. Removed that and fixed the lint issues.

File: app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt (hunk 2 above)
Comment (Maxr1998) [reply app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt]: Huh, I'd have expected a compat version of that to exist. Since it doesn't, I agree and will merge it as is.

**Review by Maxr1998 — APPROVED** [review]

**Comment by Maxr1998** [comment]
Thank you!

**Comment by simson** [comment]
I can't tell for android 14, but using android 15 i have the same issue : background stop after 30sec. I disabled all battery optimisation : allowing background usage "Unrestricted" on my pixel 6a. Is there another thing  i can do or test ?
