### PR TITLE
Set appMode for webui

### LINKED ISSUE #145: Cannot cast to Google Cast receiver
I don't have any reverse proxy issues here. This issue is experienced solely on the Kotlin app.

**To Reproduce**
1. User Playback Settings -> Nightly Chromecast Client
2. Press Save, then forceclose the app.
3. Open a cast session and begin playback.
4. Playback is attempted on the Stable Chromecast client and not the Nightly Google Cast client -- it fails. 

**Expected behavior**
Successfully casting on the nightly Google Cast client just as one would from Chrome (mobile) or the 1.0 Cordova app. As the old Chromecast caster is being deprecated in favor of a functional Google Cast client, the new Android app should share the same ability to access the Google Cast client as the old.

**System (please complete the following information):**
 - App version 2.0.0-rc.6
 - Android 11
 - Jellyfin server 10.6

**Additional context**

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
The webui needs the `appMode` property set to either `cordova` or `android` for some behavior. We didn't do that.

Relevant code in web: https://github.com/jellyfin/jellyfin-web/blob/692d404285c19e1700a74fec23b4804273d12ac3/src/components/castSenderApi.js#L3

As you can see, if the app mode is not set it will always load the cast_sender JavaScript from Google, this JS would then overwrite our own injected code. By setting the appMode it doesn't do that.

It doesn't fix most chromecast issues though.

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
Thanks to @neopc10 since #145 made me wonder why the nightly cast client didn't work. When digging into the webui code I found out we needed to set `appMode` and didn't. I know we've had some other issues complaining about casting not working but couldn't provide additional details before.

File: app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt [hunk 1]
```diff
@@ -7,11 +7,14 @@ import java.io.IOException
 
 const val JS_INJECTION_CODE = """
 !function() {
+    window['appMode'] = 'android';
```
Comment (Maxr1998) [inline app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt:10]: Might be a matter of taste, but I'd prefer this:
```suggestion
    window.appMode = 'android';
```

**Review by Maxr1998 — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt (hunk 1 above)
Comment (nielsvanvelzen) [reply app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt:10]: And I don't

Comment (Maxr1998) [reply app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt:10]: Fiiiine, then ignore my request xD

Comment (CarlosOlivo) [reply app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt:10]: A brief search in Google says that the notation by square brackets evaluates what is inside them so it is usually used when the property name is dynamic and/or has special characters but is generally associated with elements of an array, while the dot notation is shorter and is usually associated more with properties of an object, but it has some limitations in the name.

Maybe using the dot notation improves at least 3 yoctoseconds.

Well, it's JavaScript (?)

Comment (nielsvanvelzen) [reply app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt:10]: I normally use dot-notation for known properties and square bracket notation for custom properties.

**Comment by nielsvanvelzen** [comment]
I've noticed this doesn't actually fix chromecast issues but only appeared to do so while testing on one of my devices. Nothing changed on another device I have.

But in the end we still need to add the app mode so I'll change the PR title to not say a thing about casting 😂

**Review by Maxr1998 — APPROVED** [review]

**Comment by neopc10** [comment]
I just sideloaded this RC7. This merge appears to have borked the server connection process on Pixel 3 running vanilla Android 11.
Jellyfin10.6

**Comment by CarlosOlivo** [comment]
I can confirm, need to clear app data to reproduce in v2.0.0-rc.7

```
2020-09-29 14:30:56.264 21410-21410/? E/InputDispatcher: Window handle Window{3ad9faa u0 org.jellyfin.mobile.debug/org.jellyfin.mobile.MainActivity} has no registered input channel
2020-09-29 14:30:56.549 21410-21410/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(599)] "Uncaught TypeError: Cannot read property 'prototype' of undefined", source: http://192.168.100.2:8096/native/chrome.cast.js (599)
2020-09-29 14:30:57.358 21410-21410/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Uncaught (in promise) TypeError: Cannot read property 'classList' of undefined", source: http://192.168.100.2:8096/web/components/viewContainer.js?v=29 (1)
2020-09-29 14:30:57.358 21410-21410/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "RequireJS error: TypeError: Cannot read property 'classList' of undefined. Failed modules: ", source: http://192.168.100.2:8096/web/scripts/site.js (1)
```

When appMode is set to 'Android' the webUI omits the creation of the JavaScript ApiClient singleton.

https://github.com/jellyfin/jellyfin-web/blob/38398e833a2aecd40affe1594b3966540a2615ee/src/scripts/site.js#L437
https://github.com/jellyfin/jellyfin-web/blob/38398e833a2aecd40affe1594b3966540a2615ee/src/scripts/site.js#L99

Also the exception `TypeError: Cannot read property 'classList' of undefined` but I can't find the source, better to revert this for now.

Without appMode

```
2020-09-29 14:59:41.854 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "loading ApiClient singleton", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 14:59:41.854 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "creating ApiClient singleton", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 14:59:41.855 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "loaded ApiClient singleton", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 14:59:41.856 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "initAfterDependencies promises resolved", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 14:59:41.903 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "using default fonts", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 14:59:41.921 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "loading installed plugins", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/playAccessValidation/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/experimentalWarnings/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/htmlAudioPlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/htmlVideoPlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/photoPlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/bookPlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/youtubePlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/backdropScreensaver/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/logoScreensaver/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/sessionPlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/chromecastPlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): native/exoplayer", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:41.952 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): native/externalplayer", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 14:59:42.045 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "setting page base to /web", source: http://192.168.100.2:8096/web/components/appRouter.js?v=29 (1)
2020-09-29 14:59:42.055 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.", source: http://192.168.100.2:8096/web/elements/emby-button/paper-icon-button-light.js?v=29 (1)
2020-09-29 14:59:42.088 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "begin onAppReady", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 14:59:42.088 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "onAppReady: loading dependencies", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 14:59:42.211 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining core routes", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.211 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /addserver.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.213 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /selectserver.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.213 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /login.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.213 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /forgotpassword.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.213 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /forgotpasswordpin.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.214 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /mypreferencesmenu.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.214 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /myprofile.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.214 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /mypreferencesdisplay.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.214 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /mypreferenceshome.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.214 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /mypreferencesplayback.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.214 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /mypreferencessubtitles.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.214 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /dashboard.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.214 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /dashboardgeneral.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.214 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /networking.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.214 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /devices.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /device.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /dlnaprofile.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /dlnaprofiles.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /addplugin.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /library.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /librarydisplay.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /dlnasettings.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /edititemmetadata.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /encodingsettings.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /log.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /metadataimages.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /metadatanfo.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /notificationsetting.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /notificationsettings.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.215 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /playbackconfiguration.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /availableplugins.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /repositories.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /home.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /search.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /list.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /details", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /livetv.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /livetvguideprovider.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /livetvsettings.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /livetvstatus.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /livetvtuner.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /movies.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /music.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /installedplugins.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.216 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /scheduledtask.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /scheduledtasks.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /serveractivity.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /apikeys.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /streamingsettings.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /tv.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /useredit.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /userlibraryaccess.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /usernew.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /userparentalcontrol.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /userpassword.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /userprofiles.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /wizardremoteaccess.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /wizardfinish.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /wizardlibrary.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.217 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /wizardsettings.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.218 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /wizardstart.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.218 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /wizarduser.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.218 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /videoosd.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.218 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /nowplaying.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.218 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /configurationpage", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.218 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.218 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /index.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 14:59:42.220 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "serviceWorker unsupported", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 14:59:42.394 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "appRouter - processing path request /web#!/login.html", source: http://192.168.100.2:8096/web/components/appRouter.js?v=29 (1)
2020-09-29 14:59:42.395 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "appRouter - proceeding to /web#!/login.html", source: http://192.168.100.2:8096/web/components/appRouter.js?v=29 (1)
2020-09-29 14:59:42.529 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "chromecast.initialize", source: http://192.168.100.2:8096/web/plugins/chromecastPlayer/plugin.js?v=29 (1)
2020-09-29 14:59:42.546 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "chromecast init success", source: http://192.168.100.2:8096/web/plugins/chromecastPlayer/plugin.js?v=29 (1)
2020-09-29 14:59:42.547 4366-4366/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "chromecast receiver list empty", source: http://192.168.100.2:8096/web/plugins/chromecastPlayer/plugin.js?v=29 (1)
```

Whith appMode

```
2020-09-29 15:01:50.194 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "initAfterDependencies promises resolved", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 15:01:50.242 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "using default fonts", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 15:01:50.256 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "loading installed plugins", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 15:01:50.287 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/playAccessValidation/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.288 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/experimentalWarnings/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.288 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/htmlAudioPlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.288 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/htmlVideoPlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.288 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/photoPlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.288 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/bookPlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.288 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/youtubePlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.288 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/backdropScreensaver/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.288 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/logoScreensaver/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.288 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/sessionPlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.288 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): plugins/chromecastPlayer/plugin", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.288 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): native/exoplayer", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.288 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Loading plugin (via deprecated requirejs method): native/externalplayer", source: http://192.168.100.2:8096/web/components/pluginManager.js?v=29 (1)
2020-09-29 15:01:50.422 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "chromecast.initialize", source: http://192.168.100.2:8096/web/plugins/chromecastPlayer/plugin.js?v=29 (1)
2020-09-29 15:01:50.430 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "setting page base to /web", source: http://192.168.100.2:8096/web/components/appRouter.js?v=29 (1)
2020-09-29 15:01:50.438 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.", source: http://192.168.100.2:8096/web/elements/emby-button/paper-icon-button-light.js?v=29 (1)
2020-09-29 15:01:50.440 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "chromecast init success", source: http://192.168.100.2:8096/web/plugins/chromecastPlayer/plugin.js?v=29 (1)
2020-09-29 15:01:50.440 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "chromecast receiver list empty", source: http://192.168.100.2:8096/web/plugins/chromecastPlayer/plugin.js?v=29 (1)
2020-09-29 15:01:50.478 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "begin onAppReady", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 15:01:50.478 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "onAppReady: loading dependencies", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 15:01:50.620 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining core routes", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.621 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /addserver.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.622 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /selectserver.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.622 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /login.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.623 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /forgotpassword.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.623 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /forgotpasswordpin.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.623 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /mypreferencesmenu.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.623 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /myprofile.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.623 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /mypreferencesdisplay.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /mypreferenceshome.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /mypreferencesplayback.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /mypreferencessubtitles.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /dashboard.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /dashboardgeneral.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /networking.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /devices.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /device.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /dlnaprofile.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /dlnaprofiles.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /addplugin.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /library.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.624 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /librarydisplay.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.625 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /dlnasettings.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.625 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /edititemmetadata.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.625 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /encodingsettings.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.625 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /log.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.625 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /metadataimages.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.625 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /metadatanfo.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.625 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /notificationsetting.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.625 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /notificationsettings.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.625 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /playbackconfiguration.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.625 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /availableplugins.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.625 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /repositories.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.626 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /home.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.626 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /search.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.626 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /list.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /details", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /livetv.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /livetvguideprovider.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /livetvsettings.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /livetvstatus.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /livetvtuner.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /movies.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /music.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /installedplugins.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /scheduledtask.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /scheduledtasks.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /serveractivity.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /apikeys.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /streamingsettings.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /tv.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /useredit.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.627 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /userlibraryaccess.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /usernew.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /userparentalcontrol.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /userpassword.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /userprofiles.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /wizardremoteaccess.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /wizardfinish.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /wizardlibrary.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /wizardsettings.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /wizardstart.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /wizarduser.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /videoosd.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /nowplaying.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /configurationpage", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.628 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "defining route: /index.html", source: http://192.168.100.2:8096/web/scripts/routes.js?v=29 (1)
2020-09-29 15:01:50.630 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "serviceWorker unsupported", source: http://192.168.100.2:8096/web/scripts/site.js (1)
2020-09-29 15:01:50.644 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "appRouter - processing path request /web#!/selectserver.html", source: http://192.168.100.2:8096/web/components/appRouter.js?v=29 (1)
2020-09-29 15:01:50.644 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "appRouter - proceeding to /web#!/selectserver.html", source: http://192.168.100.2:8096/web/components/appRouter.js?v=29 (1)
2020-09-29 15:01:50.735 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "Uncaught (in promise) TypeError: Cannot read property 'classList' of undefined", source: http://192.168.100.2:8096/web/components/viewContainer.js?v=29 (1)
2020-09-29 15:01:50.735 4367-4367/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "RequireJS error: TypeError: Cannot read property 'classList' of undefined. Failed modules: ", source: http://192.168.100.2:8096/web/scripts/site.js (1)
```

**Comment by Maxr1998** [comment]
Oh my, we really need to get rid of the web client and build a native one that we actually control..
thanks for the detailed info @CarlosOlivo, could you add them to the issue opened at #153?
